//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tweetoys.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tweetoys.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   this command has been executed {0} times に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string wox_plugin_cmd_cmd_has_been_executed_times {
            get {
                return ResourceManager.GetString("wox_plugin_cmd_cmd_has_been_executed_times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error running the command に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string wox_plugin_cmd_command_failed {
            get {
                return ResourceManager.GetString("wox_plugin_cmd_command_failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Command not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string wox_plugin_cmd_command_not_found {
            get {
                return ResourceManager.GetString("wox_plugin_cmd_command_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string wox_plugin_cmd_execute_through_shell {
            get {
                return ResourceManager.GetString("wox_plugin_cmd_execute_through_shell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweet に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string wox_plugin_cmd_plugin_description {
            get {
                return ResourceManager.GetString("wox_plugin_cmd_plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tweetoys に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string wox_plugin_cmd_plugin_name {
            get {
                return ResourceManager.GetString("wox_plugin_cmd_plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Run as administrator (Ctrl+Shift+Enter) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string wox_plugin_cmd_run_as_administrator {
            get {
                return ResourceManager.GetString("wox_plugin_cmd_run_as_administrator", resourceCulture);
            }
        }
    }
}
